version: "3.5"

services:
  escrow-kusama-postgres:
    image: postgres:13.4-alpine
    container_name: escrow-kusama-postgres
    environment:
      POSTGRES_DB: 'escrow-kusama'
      POSTGRES_USER: 'escrow-kusama'
      POSTGRES_PASSWORD: 'test'
      POSTGRES_PORT: '5432'
      POSTGRES_INITDB_ARGS: "--auth-local=trust"
    ports:
      - 5432:5432
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - ../postgresql/escrow-kusama:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  escrow-kusama-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: escrow-kusama-node
    container_name: escrow-kusama-node
    environment:
      KUSAMA_WS_ENDPOINT: 'wss://kusama-rpc.polkadot.io'
      ADMIN_SEED: '//Alice'
      COMMISSION: '10'
      POSTGRES_URL: 'postgres://escrow-kusama:test@escrow-kusama-postgres/escrow-kusama'
      SS58_FORMAT: '2'
      KUSAMA_START_FROM_BLOCK: 'current'
      HEATHCHECK_MAX_TIMEOUT: '300'
